### ISSUE TITLE
Wrong sum of worked hours

### ISSUE THREAD

**Issue by Thiteago** [ErnaneJ/tradingworks-plus#10]
Something is causing the wrong summation of worked hours,  an example of the issue:

[screenshot](https://cdn.discordapp.com/attachments/1082670704010473523/1088176003693674566/image.png)

**Comment by ErnaneJ** [comment]
It was not possible to replicate the problem, however, I found some points with possible failures that could cause, even if intermittently, this case that you reported.

Check PR #11, test the new version and let me know if the problem persists. Anyway, I will close this discussion. You can always open a new one whenever you want or need it. Thanks.
