### ISSUE TITLE
Change message when user works exactly the work time defined

### ISSUE THREAD

**Issue by Thiteago** [ErnaneJ/tradingworks-plus#32]
When user complies exactly the work he defined on settings, the extension show an message saying "left 0:00 hours and 0 minutes", i think it's better if has an specific message for this.

![image](https://github.com/ErnaneJ/tradingworks-plus/assets/42258486/e1490277-2316-4c8b-a648-b96b9b8c664e)

**Comment by ErnaneJ** [comment]
This was resolved in #33.
