### ISSUE TITLE
Atualizar para a nova versão do TW

### ISSUE THREAD

**Issue by carloshendvpm** [ErnaneJ/tradingworks-plus#40]

**Comment by ErnaneJ** [comment]
Olá @carloshendvpm, você pode experimentar a versão beta dessa atualização utilizando a branch [`twp-v2`](https://github.com/ErnaneJ/tradingworks-plus/tree/twp-v2) ou até mesmo acompanhar/contruibuir com o seu desenvolvimento através do PR #41 relacionado à mesma branch. Obrigado!
